Knyazeva Anastasia: homework 3
frewerins/react-course pull request #1
Opened 2021-10-07 09:58 UTC by frewerins

2021-10-09 16:43 UTC, dshuran requested changes

2021-10-09 16:43 UTC, dshuran commented on myapp/src/Clock.jsx
> +      currentState: Number(props.initialState)
Вот это мощь. Использование Number :) 
Предлагаю просто изначально передавать в JSX в виде пропсов число (через фигурные скобочки), а не строку, и не нужны будут такие конструкции. Это прям экзотика)

2021-10-09 16:43 UTC, dshuran commented on myapp/src/Clock.jsx
> +      currentState: Number(props.initialState)
Ещё не очень нравятся названия переменных: currentState, initialState - что за состояние, чёрт его пойми. Если это значение счётчика, то давай так его и назовём. Чтобы незнакомому человеку сразу было понятно

2021-10-09 16:43 UTC, dshuran commented on myapp/src/Clock.jsx
> +    setTimeout(() => {clearInterval(this.timer)}, 10000);
Ну не-ет, не надо так :)
Предлагается выполнять эту проверку (на сброс таймера) в коде функции, которая устанавливает состояние. А то потом захотим изменить число тиков до 15, то придётся не забыть, что и здесь нужно всё изменить. Более того, не факт, что этот код выполнится ровно через 10 секунд, и тогда вообще могут быть проблемы.

2021-10-09 16:43 UTC, dshuran commented on myapp/src/App.js
> +      <Clock name="first" initialState="10"/>
Хотим, чтобы первый счётчик начинал отсчёт с 0, а второй с 10.

2021-10-10 08:07 UTC, frewerins commented on myapp/src/Clock.jsx
> +    setTimeout(() => {clearInterval(this.timer)}, 10000);
Сделала)

2021-10-10 08:07 UTC, frewerins commented on myapp/src/Clock.jsx
> +      currentState: Number(props.initialState)
Ой блин, а я чет не догадалась до этого(( Спасибо!

2021-10-11 07:03 UTC, dshuran requested changes

2021-10-11 07:03 UTC, dshuran commented on myapp/src/Clock.jsx
> +      numberOfTicks: props.numberOfTicks ?? 10
numberOfTicks никак не используется при рендере. Следовательно, его не нужно хранить в state. При необходимости завести дополнительное поле можно это поле хранить в классе как обычное свойство. Однако, если сделать совсем красиво, то это дополнительное свойство здесь в принципе не нужно - всю информацию можно взять из state.currentCounter и props.initialNumberOfCounter.

2021-10-11 11:46 UTC, frewerins commented on myapp/src/Clock.jsx
> +      numberOfTicks: props.numberOfTicks ?? 10
Вообще я это поле добавила для того, чтобы можно было легко поменять количество тиков в счетчике
Его точно стоит убрать?

2021-10-16 18:48 UTC, dshuran approved these changes

2021-10-16 18:49 UTC, merged